name: CI - Lint Markdown

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  md-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files
        run: ls -la
